#ifndef Wilson_Android_Message_h
#define Wilson_Android_Message_h

enum  // node event id
{
    MSG_TYPE_REGOK,
    MSG_TYPE_REGFAIL,
    MSG_TYPE_USB_NOT_READY,
    MSG_TYPE_USB_READY,
    MSG_TYPE_USB_WRITE_FAIL,
    MSG_TYPE_USB_WRITE_DONE,
    MSG_TYPE_USB_WRITE_WAIT,
    MSG_TYPE_USB_LOGCAT_WAIT,
    MSG_TYPE_USB_LOGCAT_FAIL,
    MSG_TYPE_USB_LOGCAT_DONE,
    MSG_TYPE_MICOM_UPDATE_START,
    MSG_TYPE_MICOM_UPDATE_DONE,
    MSG_TYPE_MICOM_UPDATE_FAIL,
    MSG_TYPE_NONE
};

#define MSG_KEYWORD(name) MSG_TYPE_##name
#endif
